// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acdanwdnnojtihxsplkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjZGFud2Rubm9qdGloeHNwbGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzMxNzEsImV4cCI6MjA2MTk0OTE3MX0.bnCy5tNYZqpJDCtGoPBK1Oht_33ZoIuXFLAsxn8xAfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);